[
    {"chapter": 1, "verse": 7, "text": "The fear of the LORD is the beginning of knowledge, but fools despise wisdom and instruction."},
    {"chapter": 1, "verse": 8, "text": "Listen, my son, to your father's instruction and do not forsake your mother's teaching."},
    {"chapter": 2, "verse": 6, "text": "For the LORD gives wisdom; from his mouth come knowledge and understanding."},
    {"chapter": 3, "verse": 5, "text": "Trust in the LORD with all your heart and lean not on your own understanding."},
    {"chapter": 3, "verse": 11, "text": "My son, do not despise the LORD's discipline, and do not resent his rebuke."},
    {"chapter": 4, "verse": 23, "text": "Above all else, guard your heart, for everything you do flows from it."},
    {"chapter": 5, "verse": 21, "text": "For your ways are in full view of the LORD, and he examines all your paths."},
    {"chapter": 6, "verse": 6, "text": "Go to the ant, you sluggard; consider its ways and be wise!"},
    {"chapter": 6, "verse": 16, "text": "There are six things the LORD hates, seven that are detestable to him:"},
    {"chapter": 7, "verse": 1, "text": "My son, keep my words and store up my commands within you."},
    {"chapter": 8, "verse": 10, "text": "Choose my instruction instead of silver, knowledge rather than choice gold."},
    {"chapter": 9, "verse": 10, "text": "The fear of the LORD is the beginning of wisdom, and knowledge of the Holy One is understanding."},
    {"chapter": 10, "verse": 12, "text": "Hatred stirs up conflict, but love covers over all wrongs."},
    {"chapter": 10, "verse": 22, "text": "The blessing of the LORD brings wealth, without painful toil for it."},
    {"chapter": 11, "verse": 25, "text": "A generous person will prosper; whoever refreshes others will be refreshed."},
    {"chapter": 12, "verse": 1, "text": "Whoever loves discipline loves knowledge, but whoever hates correction is stupid."},
    {"chapter": 12, "verse": 18, "text": "The words of the reckless pierce like swords, but the tongue of the wise brings healing."},
    {"chapter": 13, "verse": 3, "text": "Those who guard their lips preserve their lives, but those who speak rashly will come to ruin."},
    {"chapter": 14, "verse": 29, "text": "Whoever is patient has great understanding, but one who is quick-tempered displays folly."},
    {"chapter": 15, "verse": 1, "text": "A gentle answer turns away wrath, but a harsh word stirs up anger."},
    {"chapter": 15, "verse": 33, "text": "Wisdom's instruction is to fear the LORD, and humility comes before honor."},
    {"chapter": 16, "verse": 3, "text": "Commit to the LORD whatever you do, and he will establish your plans."},
    {"chapter": 16, "verse": 9, "text": "In their hearts humans plan their course, but the LORD establishes their steps."},
    {"chapter": 17, "verse": 22, "text": "A cheerful heart is good medicine, but a crushed spirit dries up the bones."},
    {"chapter": 18, "verse": 10, "text": "The name of the LORD is a fortified tower; the righteous run to it and are safe."},
    {"chapter": 19, "verse": 20, "text": "Listen to advice and accept discipline, and at the end you will be counted among the wise."},
    {"chapter": 20, "verse": 24, "text": "A person's steps are directed by the LORD. How then can anyone understand their own way?"},
    {"chapter": 21, "verse": 21, "text": "Whoever pursues righteousness and love finds life, prosperity, and honor."},
    {"chapter": 22, "verse": 6, "text": "Start children off on the way they should go, and even when they are old they will not turn from it."},
    {"chapter": 22, "verse": 9, "text": "The generous will themselves be blessed, for they share their food with the poor."},
    {"chapter": 23, "verse": 12, "text": "Apply your heart to instruction and your ears to words of knowledge."},
    {"chapter": 23, "verse": 23, "text": "Buy the truth and do not sell it— wisdom, instruction and insight as well."},
    {"chapter": 24, "verse": 3, "text": "By wisdom a house is built, and through understanding it is established."},
    {"chapter": 24, "verse": 14, "text": "Know also that wisdom is like honey for you: If you find it, there is a future hope for you, and your hope will not be cut off."},
    {"chapter": 25, "verse": 11, "text": "A word fitly spoken is like apples of gold in settings of silver."},
    {"chapter": 25, "verse": 28, "text": "Like a city whose walls are broken through is a person who lacks self-control."},
    {"chapter": 26, "verse": 12, "text": "Do you see a person wise in their own eyes? There is more hope for a fool than for them."},
    {"chapter": 27, "verse": 1, "text": "Do not boast about tomorrow, for you do not know what a day may bring."},
    {"chapter": 27, "verse": 17, "text": "As iron sharpens iron, so one person sharpens another."},
    {"chapter": 28, "verse": 13, "text": "Whoever conceals their sins does not prosper, but the one who confesses and renounces them finds mercy."},
    {"chapter": 28, "verse": 26, "text": "Those who trust in themselves are fools, but those who walk in wisdom are kept safe."},
    {"chapter": 29, "verse": 11, "text": "Fools give full vent to their rage, but the wise bring calm in the end."},
    {"chapter": 29, "verse": 25, "text": "Fear of man will prove to be a snare, but whoever trusts in the LORD is kept safe."},
    {"chapter": 30, "verse": 5, "text": "Every word of God is flawless; he is a shield to those who take"}
  ]
  